language: rust

matrix:
  include:
    - rust: stable
      script:
        - cargo test
    - rust: beta
      script:
        - cargo test --features beta
        - cargo test --features beta --release
