language: rust

matrix:
  include:
    - rust: stable
      script:
        - cargo test
        - cargo test --release
    - rust: beta
      script:
        - cargo test
        - cargo test --release
