[package]
name = "once_cell"
version = "0.0.1"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
categories = [ "rust-patterns" ]
repository = "https://github.com/matklad/once_cell"
description = """
Lazy and lazy static values without macros
"""
license = "MIT OR Apache-2.0"
